<h2>USWATUN KHASANAH<h2>

1. Buatlah sebuah list dengan 5 buah angka acak antara 1 sampai 10.

In [ ]:
# Tulis kode disini
list = [1, 3, 5, 7, 9]
list

[1, 3, 5, 7, 9]

2. Ubah list tersebut menjadi tuple.

In [ ]:
# Tulis kode disini
list = [1, 3, 5, 7, 9]
print(tuple(list))

(1, 3, 5, 7, 9)


3. Tambahkan angka acak lainnya ke dalam tuple (ingat bahwa tuple tidak bisa diubah, jadi anda harus membuat tuple baru).

In [ ]:
# Tulis kode disini
list1 = [8, 6, 2, 4, 10]
list2 = tuple(list1)
list3 = (1, 5)
hasil = list2 + list3
print(type(hasil))

<class 'tuple'>
<class 'tuple'>


4. Buatlah sebuah fungsi yang menerima tuple angka dan mengembalikan tuple dengan elemen yang terurut.

In [ ]:
# Tulis kode disini
list2 = [8, 6, 2, 4, 10]
list3 = tuple(list2)
sorted_tuple = sorted(list3)
print(type(sorted_tuple))

<class 'list'>


5. Buat array Numpy 1D yang berisi 5 bilangan bulat acak dari 1 sampai 10.

In [ ]:
# Tulis kode disini
import numpy as np

a = np.array([6, 9, 8, 4, 2])
a

array([6, 9, 8, 4, 2])

6. Hitung mean, median, dan standar deviasi dari array tersebut.
Code Jawabannya:

In [ ]:
# Tulis kode disini
import numpy as np

a = np.array([2, 4, 6, 8, 10])
mean = np.mean(a)
median = np.median(a)
std_dev = np.std(a)

print(a)
print("Mean : " ,mean)
print("Median : " ,median)
print("standar deviasi : " ,std_dev)

[ 2  4  6  8 10]
Mean :  6.0
Median :  6.0
standar deviasi :  2.8284271247461903


7. Buatlah array 2D (3x3) yang berisi angka acak.

In [ ]:
# Tulis kode disini
import numpy as np

a = np.array([[1, 2, 3], [4, 8, 9], [4, 9, 1]])
a

array([[1, 2, 3],
       [4, 8, 9],
       [4, 9, 1]])

8. Datar atau flatten array 2D tersebut menjadi array 1D.

In [ ]:
# Tulis kode disini
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b = a.flatten()
print(b)

[1 2 3 4 5 6 7 8 9]


9. Buatlah DataFrame Pandas sederhana yang berisi data nama, usia, dan kota dari 3 orang.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Risma', 'Lusy', 'Wulan'],
    'Usia': [22, 20, 22],
    'Kota': ['Tulungagung', 'Gresik', 'Tulungagung']
}

df = pd.DataFrame(data)

print(df)

    Nama  Usia         Kota
0  Risma    22  Tulungagung
1   Lusy    20       Gresik
2  Wulan    22  Tulungagung


10. Tambahkan kolom 'Pekerjaan' ke DataFrame tersebut.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Risma', 'Lusy', 'Wulan'],
    'Usia': [22, 20, 22],
    'Kota': ['Tulungagung', 'Gresik', 'Tulungagung'],
}

df = pd.DataFrame(data)
df ['pekerjaan'] = ['Pengusaha', 'Pengusaha', 'Selebgram']

print(df)

    Nama  Usia         Kota  Pekerjaan
0  Risma    22  Tulungagung  Pengusaha
1   Lusy    20       Gresik  Pengusaha
2  Wulan    22  Tulungagung  Selebgram


11. Ubahlah usia salah satu nama menjadi 31.

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Risma', 'Lusy', 'Wulan'],
    'Usia': [22, 20, 22],
    'Kota': ['Tulungagung', 'Gresik', 'Tulungagung'],
    'Pekerjaan': ['Pengusaha', 'Pengusaha', 'Selebgram']
}

df = pd.DataFrame(data)

df.loc[df['Nama'] == 'Lusy', 'Usia'] = 21

print(df)

    Nama  Usia         Kota  Pekerjaan
0  Risma    22  Tulungagung  Pengusaha
1   Lusy    21       Gresik  Pengusaha
2  Wulan    22  Tulungagung  Selebgram


12. Urutkan DataFrame berdasarkan usia dari yang muda ke yang tua.
Code Jawabannya:

In [ ]:
# Tulis kode disini
import pandas as pd

data = {
    'Nama': ['Risma', 'Lusy', 'Wulan'],
    'Usia': [22, 20, 22],
    'Kota': ['Tulungagung', 'Gresik', 'Tulungagung'],
    'Pekerjaan': ['Pengusaha', 'Pengusaha', 'Seleb']
}

df = pd.DataFrame(data)

df_urut_usia = df.sort_values(by='Usia')

print(df_urut_usia)

    Nama  Usia         Kota  Pekerjaan
0  Risma    22  Tulungagung  Pengusaha
2  Wulan    22  Tulungagung      Seleb
1   Lusy    30       Gresik  Pengusaha
